### ISSUE TITLE
Power Systems Economics PUC - RIO 2019.2

### ISSUE THREAD

**Issue by andrewrosemberg** [andrewrosemberg/HydroPowerModels.jl#19] opened 2019-10-11 17:03 UTC
This issue is for questions about studies using the Package

**Comment by Veronicafeijao** [comment] 2019-10-12 00:54
Which version of Julia should I use?

**Comment by GabrielCalvo2812** [comment] 2019-10-12 19:47
So I am trying to install the SDDP package in JuliaPro, but turns out that the installation does not conclude due to a package called MathOptFormat. Apparently, I succeded in installing the SDDP in Julia by the way, but it seems that I have to install for juliaPro as well, because when I call "using SDDP", it can not find it.
![image](https://user-images.githubusercontent.com/54291241/66706942-e2fc7900-ed0f-11e9-964d-b17af3b70ff4.png)

**Comment by GabrielCalvo2812** [comment] 2019-10-12 20:44
Also, I have another issue, this time with HydroPowerModels. It seems the file called Cairo was not able to be downloaded as installing proccess was running. Now, when I call using HydroPowerModels I have the warnning below:
![image](https://user-images.githubusercontent.com/54291241/66707502-dc71ff80-ed17-11e9-97ae-e4526261d2e5.png)

**Comment by Veronicafeijao** [comment] 2019-10-12 22:03
When I use ATOM, I also have problem with MathOptFormat. Now, I'm not using ATOM and the problem is with package HTTP (to install SDDP.jl) @andrewrosemberg , what's the problem?

**Comment by GabrielCalvo2812** [comment] 2019-10-12 22:07
@Veronicafeijao  which IDE are you using?

**Comment by Veronicafeijao** [comment] 2019-10-12 22:12
I went in ATOM>Julia>Open REPL. There I put: (julia> ] add https://github.com/odow/SDDP.jl/#master )

**Comment by GabrielCalvo2812** [comment] 2019-10-12 22:31
Well, I took a chance on your suggestion, now have problem with both MathOptFormat and HTTP
![image](https://user-images.githubusercontent.com/54291241/66708444-ee0ed380-ed26-11e9-9f26-caef0e5021a6.png)

**Comment by andrewrosemberg** [comment] 2019-10-13 15:27
> Which version of Julia should I use?

I have been using Julia 1.0 up to 1.05 to test the code, so those versions are preferred, but I believe it should work with later versions of Julia.

**Comment by andrewrosemberg** [comment] 2019-10-13 15:34
@Veronicafeijao and @GabrielCalvo2812, sometimes there are issues installing SDDP. A solution provided in one of the package's issue (https://github.com/odow/SDDP.jl/issues/182#issuecomment-474058537) is to first add MathOptFormat.jl:

```
] add https://github.com/odow/MathOptFormat.jl

] add https://github.com/odow/SDDP.jl
```

**Comment by andrewrosemberg** [comment] 2019-10-13 15:38
> Also, I have another issue, this time with HydroPowerModels in Julia itself. It seems the file called Cairo was not able to be downloaded as installing proccess was running. Now, when I call using HydroPowerModels I have the warnning below:

@GabrielCalvo2812, I believe once you have SDDP properly installed, HydroPowerModels will successfully build and then using it will not produce these errors. If it persists, let me know.

**Comment by Veronicafeijao** [comment] 2019-10-13 16:13
But SDDP already was installed with success. And even so Hydropowermodels has problem with Cairo.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by odow** [comment] 2019-10-13 16:15
I'm trying to get SDDP.jl registered (https://github.com/JuliaRegistries/General/pull/4247), so once it is, this should resolve the version issues. 

I believe that the issue is that JuliaPro includes a version of HTTP.jl that is missing a required bug-fix for MathOptFormat (we need 0.8.2+). So I would try
```Julia
] add HTTP
```
Then run `] st` and check that HTTP is at least version 0.8.2. Then run
```Julia
] add MathOptFormat
] add https://github.com/odow/SDDP.jl
```

Once that's done, you can add HydroPowerModels.

If you get the `libcairo` error, try `] add Cairo` or `] build Cairo`.

**Comment by djiegow** [comment] 2019-10-13 17:06
> > Which version of Julia should I use?
> 
> I have been using Julia 1.0 up to 1.05 to test the code, so those versions are preferred, but I believe it should work with later versions of Julia.

@andrewrosemberg, I was using Julia 1.2. I added the MathOptFormat, SDDP and HydroPowerModels and I had this problem below:

![Screen Shot 2019-10-13 at 13 49 12](https://user-images.githubusercontent.com/42680186/66719147-2c0d0580-edc2-11e9-9d69-1ea35bbd42f0.png)

I also failed in building "Fontconfig".

![Screen Shot 2019-10-13 at 14 04 10](https://user-images.githubusercontent.com/42680186/66719159-5eb6fe00-edc2-11e9-9d02-3f34461ab5b1.png)

After this, I tried Julia 1.0.5. And I had another problem:

![Screen Shot 2019-10-13 at 14 05 04](https://user-images.githubusercontent.com/42680186/66719163-7d1cf980-edc2-11e9-9505-6a6fc0ebb915.png)

Am I forgetting anything? 

Thanks!

**Comment by andrewrosemberg** [comment] 2019-10-13 18:11
@djiegow, could you send me the output of your project status : 
`] st`

**Comment by GabrielCalvo2812** [comment] 2019-10-13 23:21
@odow I tried your suggestion, I used the command add HTTP and it updated some files, but then using ] st it did not show which version was on the files:

![image](https://user-images.githubusercontent.com/54291241/66724007-c7b86900-edf6-11e9-8544-6cc99ff0b1ab.png)

Actually I looked for in the files explorer for the HTTP package in juliaPro1.2 and wasn't there ( don't mind about HydroPowerModels, it is corrupted anyway):

![image](https://user-images.githubusercontent.com/54291241/66724023-00f0d900-edf7-11e9-9d71-f6e7858b54f6.png)

**Comment by andrewrosemberg** [comment] 2019-10-14 01:27
@GabrielCalvo2812 I would start a new project from scratch to test adding the necessary packages

**Comment by GabrielCalvo2812** [comment] 2019-10-14 01:34
@andrewrosemberg what you mean with a new project? I am just installing the packages

**Comment by djiegow** [comment] 2019-10-14 15:25
> @djiegow, could you send me the output of your project status :
> `] st`

Sure!

![Screen Shot 2019-10-14 at 11 41 55](https://user-images.githubusercontent.com/42680186/66763099-a058af00-ee7d-11e9-8ddc-ce7c648deb21.png)

**Comment by andrewrosemberg** [comment] 2019-10-14 18:21
[teste_hydropowermodels.zip](https://github.com/andrewrosemberg/HydroPowerModels.jl/files/3725797/teste_hydropowermodels.zip)

Hi Guys,

This is a small project with a basic script to test the package. I would advise using this as a start.
The above folder contains a test script, a case folder, and a Julia environment (Project.toml and Manifest.toml). 

The lines 

```
using Pkg
Pkg.activate(".")
Pkg.instantiate()
```

will activate the environment and download all the necessary packages at their proper version (SDDP, HydroPowerModels, GLPK).

Please let me know if this doesn't run as intended.

**Comment by andrewrosemberg** [comment] 2019-10-14 18:25
I also just fixed the plotting error

`ERROR: Cannot convert Tuple{Array{Float64,2},Array{Float64,2}} to series data for plotting`

 (caused by an unexpected bug at the new version of [Plots.jl](https://github.com/JuliaPlots/Plots.jl/issues/2185#issue-492975362)).

**Comment by ncihangir** [comment] 2019-10-14 20:01
Hello, I am using JuliaPro 1.2.0. Just tried to run the test script, but still getting the same error. Please see below. Thank you!

![image](https://user-images.githubusercontent.com/56561199/66779210-9c3b8a00-ee9b-11e9-8c71-3de53cb50039.png)
![image](https://user-images.githubusercontent.com/56561199/66779294-bf663980-ee9b-11e9-8342-0b663871f7da.png)

![image](https://user-images.githubusercontent.com/56561199/66779268-ad849680-ee9b-11e9-8eb8-a21b0bee99be.png)

**Comment by andrewrosemberg** [comment] 2019-10-14 20:05
@ncihangir could you send the output from the activate+instantiate call?

**Comment by ncihangir** [comment] 2019-10-14 21:41
Hello Andrew, please see below. It gives "resolving package versions" for quite a long time and seems like not able to complete:
![image](https://user-images.githubusercontent.com/56561199/66784903-bda37280-eea9-11e9-9239-d43d14dd4564.png)

**Comment by andrewrosemberg** [comment] 2019-10-14 22:16
@ncihangir the output from the activate function shows you are not running this section on the folder of test_hydropowermodels. 

You have to run those commands in the same folder of the Project.toml and Manifest.tml.

**Comment by thamires-bap** [comment] 2019-10-15 00:58
Hey, @andrewrosemberg ! I tried to run the test, but when I tried it I got this message:
![Erro 1](https://user-images.githubusercontent.com/56554285/66792086-85ae2680-eecd-11e9-9ed1-d122b247b200.jpeg)

And then I tried adding the package:
![Erro 2](https://user-images.githubusercontent.com/56554285/66792108-9fe80480-eecd-11e9-981a-fa5c1bf0d2c4.jpeg)

 but it didn't work as well...

Could you help me please?

I think I might be doing something wrong. Do I have to do something specific to install HydroPowerModels?

Thanks a lot!

**Comment by odow** [comment] 2019-10-15 02:05
@thamires-bap it looks like you're not running the command from the right folder.

To update [Andrew's comment](https://github.com/andrewrosemberg/HydroPowerModels.jl/issues/19#issuecomment-541838959):
1. Download https://github.com/andrewrosemberg/HydroPowerModels.jl/files/3725797/teste_hydropowermodels.zip and unzip it somewhere nice (like `~/Documents/HydroPowerModels/`).
2. Open Julia (or Atom) (or Juno)
3. Run `cd("~/Documents/HydroPowerModels/")` (or wherever you saved it.) The path should be such that "~/Documents/HydroPowerModels/Manifest.toml" points to the one you extracted from the zip file
4. Run `using Pkg; Pkg.activate("."); Pkg.instantiate()`

**Comment by JJhern** [comment] 2019-10-15 10:20
@andrew I am getting this  error: https://github.com/andrewrosemberg/HydroPowerModels.jl/issues/19#issuecomment-541840824

How did you fixe it ?

**Comment by thamires-bap** [comment] 2019-10-15 10:21
Hey, @odow ! I did just as you said, but the result was this:
![Captura de Tela 2019-10-15 às 07 19 48](https://user-images.githubusercontent.com/56554285/66823319-5d99e400-ef1c-11e9-9d06-0c7ba33ba8e4.png)

**Comment by mflb** [comment] 2019-10-15 11:16
Hey, @andrewrosemberg ! I tried to run the test script, but I am getting some errors.
Please see below. 

![Capturar1](https://user-images.githubusercontent.com/56460128/66826561-17944e80-ef23-11e9-98c1-009ffe88b245.PNG)

![Capturar2](https://user-images.githubusercontent.com/56460128/66826572-1cf19900-ef23-11e9-9483-2bd0aca62646.PNG)

![Capturar3](https://user-images.githubusercontent.com/56460128/66826581-224ee380-ef23-11e9-85f0-b9c2c015d5fc.PNG)

Could you help me, please?
Thank you!

**Comment by ncihangir** [comment] 2019-10-15 12:29
Hello, I also get similar error as Thamires when running Pkg.instantiate( ). 
![image](https://user-images.githubusercontent.com/56561199/66831507-d0f42380-ef25-11e9-896c-6c27b6839744.png)

**Comment by andrewrosemberg** [comment] 2019-10-15 13:04
@thamires-bap and @ncihangir searching about your problem in google I found this: https://discourse.julialang.org/t/pkg-instantiate-fails/11709/7

Maybe try the fix at the end of this issue. It seems like Windows is having a protocol problem unrelated to the package.

**Comment by andrewrosemberg** [comment] 2019-10-15 13:18
@mflb, your issue is from [TimeZones.jl](https://github.com/JuliaTime/TimeZones.jl/issues/154). It doesn't recognize 'America/Sao_Paulo' as a valid time zone. A quick fix as proposed [here](https://github.com/GenieFramework/Genie.jl/issues/59) is to change the timezone of your system.

**Comment by Veronicafeijao** [comment] 2019-10-15 13:18
@mflb , I had a similar problem, but with other different files. I resolved by opening the entire test_hydropowermodels folder with the atom in File> Open folder. Then File> open file> (teste.jl). When I ran, these errors no appeared.
Try it

**Comment by andrewrosemberg** [comment] 2019-10-15 13:20
> @andrewrosemberg I am getting this error: [#19 (comment)](https://github.com/andrewrosemberg/HydroPowerModels.jl/issues/19#issuecomment-541840824)
> 
> How did you fix it ?

@JJhern Just update our package and it will be solved. I have downgraded Plots.jl to version "0.26.0", since the new version "0.27.0" had an issue.

**Comment by Veronicafeijao** [comment] 2019-10-15 13:21
@mflb, Andrew helped you in the first problem(America/Sao Paulo), and I was talking about the next problems.

**Comment by lopeesfelipe** [comment] 2019-10-16 00:13
I guess the Plots.jl issue was not solved with it's downgrade.. I already updated the package and it is using the version "0.26.3" of Plots.jl. I also tried to downgrade to version "0.26.0", but the issue persists.

![image](https://user-images.githubusercontent.com/36933919/66878396-07668880-ef90-11e9-802c-a33f782f0e27.png)

**Comment by hernanijj** [comment] 2019-10-16 00:48
> > @andrewrosemberg I am getting this error: [#19 (comment)](https://github.com/andrewrosemberg/HydroPowerModels.jl/issues/19#issuecomment-541840824)
> > How did you fix it ?
> 
> @JJhern Just update our package and it will be solved. I have downgraded Plots.jl to version "0.26.0", since the new version "0.27.0" had an issue.

it is still not working @andrewrosemberg

**Comment by andrewrosemberg** [comment] 2019-10-16 02:19
@lopeesfelipe @hernanijj the examples are being executed with plots 0.26.0 in the docs. Please verify you are not using old precompilations of HydroPowerModels.

**Comment by lopeesfelipe** [comment] 2019-10-16 02:54
You're right, but when I update the HydroPowerModels package (with the command ] add https://github.com/andrewrosemberg/HydroPowerModels.jl.git) it's used Plots.jl  in 0.26.3 version.

![image](https://user-images.githubusercontent.com/36933919/66884153-a7c7a780-efa6-11e9-8cd5-74c38e8a2abe.png)

![image](https://user-images.githubusercontent.com/36933919/66884165-b2823c80-efa6-11e9-9c77-c569d73d05bf.png)

**Comment by andrewrosemberg** [comment] 2019-10-16 15:01
> You're right, but when I update the HydroPowerModels package (with the command ] add https://github.com/andrewrosemberg/HydroPowerModels.jl.git) it's used Plots.jl in 0.26.3 version.

@lopeesfelipe I don't believe this is a problem, but, all the same, instantiate should be installing 0.26.0.

**Comment by ncihangir** [comment] 2019-10-16 15:36
Hello all, I am in the room 430, Andrew will be available for some questions.Please Feel free to join. Nuran

**Comment by andrewrosemberg** [comment] 2019-10-16 16:44
@lopeesfelipe what might happen is that, if you start adding or updating packages after the "instantiate" command, Plots can update to v0.26.3 (where indeed the bug already exists). If you don't feel like instantiating again the original environment, do the following:

```
] add Plots#v0.26.0
] pin Plots
```

**Comment by andrewrosemberg** [comment] 2019-10-18 00:50
Hi Guys,

Some have asked me about LMPs (Nodal price or PLDs in Portuguese). Following the PowerModels output, they are called 'lam_kcl_r' and are inside the bus solution dictionary (PS.: they are acctualy the negative of the LMPs). So, to access the different scenarious, do the following:
```
# circuit MVA
baseMVA = results[:data][1]["powersystem"]["baseMVA"]
# LMPs
nbus = length(results[:data][1]["powersystem"]["bus"])
idxbus = collect(1:nbus)
scen_lmp = convert(Array{Array{Float64,2},1},[[-results[:simulations][i][j][:powersystem]["solution"]["bus"]["$bus"]["lam_kcl_r"] for i=1:nsim, j=1:nstages]' for bus =1:nbus])/baseMVA
```

**Comment by andrewrosemberg** [comment] 2019-10-18 01:12
In order to set different demands for each stage manually, one may use the 'set_active_demand!' funtion:
```
HydroPowerModels.set_active_demand!(data,demand)
```
where demand should be a `Array{Float64,2}`.

**Comment by andrewrosemberg** [comment] 2019-10-18 04:03
For those trying to plot the future cost function, there isn't a function for this yet ([SDDP.jl's issue](https://github.com/odow/SDDP.jl/issues/223)). 

I have implemented a simple function to help until a better solution appears:
 ```
using Plots

function plot_cuts(model::SDDP.PolicyGraph{T};node_idx::Int=1) where {T}
    node_name_parser = SDDP._node_name_parser
    cuts = Dict{String, Any}[]
    node= model.nodes[1];
    if node.objective_state !== nothing
        error("Unable to write cuts to file because model contains " *
                "objective states.")
    end

    states = vcat([[values(stat.state)...] for stat in model[1].bellman_function.global_theta.cut_oracle.states]...)
    
    ncuts = length(node.bellman_function.global_theta.cut_oracle.cuts)
    plt = plot() #Array{Plots.Plot}(undef, ncuts)

    for i = 1:ncuts
        cut = node.bellman_function.global_theta.cut_oracle.cuts[i]
        cut_coef_aux = [values(copy(cut.coefficients))...][:,:]
        vals = cut.intercept .- states*cut_coef_aux

        plot!(plt,states,vals)
    end
    
    return plot(plt, legend=false)

end
 ```

**Comment by felipefmds** [comment] 2019-10-29 03:04
Hi @andrewrosemberg . How can I do to get reservoir volume for each simulation (from 1 to 100) and scenario (1 to 12) ?
Thank you.

**Comment by andrewrosemberg** [comment] 2019-10-29 20:40
Hi Guys,

If you are trying to get the sampled inflows:

```
scen_inflows = convert(Array{Array{Float64,2},1},[[results[:data][1]["hydro"]["Hydrogenerators"][res]["inflow"][cidx(j,results[:data][1]["hydro"]["size_inflow"][1]),results[:simulations][i][j][:noise_term]] for i=1:nsim, j=1:nstages]' for res = 1:results[:data][1]["hydro"]["nHyd"]])
```

**Comment by andrewrosemberg** [comment] 2019-10-30 19:57
FAQ: Dual and primal variables are changing if more SDDP iterations are executed even though it already has statistically converged. Is this expected?

Answer: Yes, a more conservative notion of convergence would require both primal variable stalling and dual variable stalling. For case 3, this happens around the 1000th iteration.

**Comment by odow** [comment] 2019-10-30 21:34
> FAQ: Dual and primal variables are changing if more SDDP iterations are executed even though it already has statistically converged. Is this expected?
>
> Answer: Yes, a more conservative notion of convergence would require both primal variable stalling and dual variable stalling. For case 3, this happens around the 1000th iteration.

I'm so glad this came up. For those interested, see https://github.com/odow/SDDP.jl/issues/178. I recommend plotting the solution every X iterations until you "see" it stabilize.

**Closed** 2020-10-27 12:00 UTC
Labels: discussion
